/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ErrorCode = {
  NameExists: "NAME_EXISTS",
  NotFound: "NOT_FOUND",
  CollectionPinned: "COLLECTION_PINNED",
  ConcurrentHierarchyEdit: "CONCURRENT_HIERARCHY_EDIT",
  HeightViolation: "HEIGHT_VIOLATION",
  WidthViolation: "WIDTH_VIOLATION",
  NoPermissions: "NO_PERMISSIONS",
} as const;
export type ErrorCode = ClosedEnum<typeof ErrorCode>;

export type CollectionErrorData = {
  errorCode: ErrorCode;
};

export class CollectionError extends Error {
  errorCode: ErrorCode;

  /** The original data that was passed to this error instance. */
  data$: CollectionErrorData;

  constructor(err: CollectionErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.errorCode = err.errorCode;

    this.name = "CollectionError";
  }
}

/** @internal */
export const ErrorCode$inboundSchema: z.ZodNativeEnum<typeof ErrorCode> = z
  .nativeEnum(ErrorCode);

/** @internal */
export const ErrorCode$outboundSchema: z.ZodNativeEnum<typeof ErrorCode> =
  ErrorCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorCode$ {
  /** @deprecated use `ErrorCode$inboundSchema` instead. */
  export const inboundSchema = ErrorCode$inboundSchema;
  /** @deprecated use `ErrorCode$outboundSchema` instead. */
  export const outboundSchema = ErrorCode$outboundSchema;
}

/** @internal */
export const CollectionError$inboundSchema: z.ZodType<
  CollectionError,
  z.ZodTypeDef,
  unknown
> = z.object({
  errorCode: ErrorCode$inboundSchema,
})
  .transform((v) => {
    return new CollectionError(v);
  });

/** @internal */
export type CollectionError$Outbound = {
  errorCode: string;
};

/** @internal */
export const CollectionError$outboundSchema: z.ZodType<
  CollectionError$Outbound,
  z.ZodTypeDef,
  CollectionError
> = z.instanceof(CollectionError)
  .transform(v => v.data$)
  .pipe(z.object({
    errorCode: ErrorCode$outboundSchema,
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionError$ {
  /** @deprecated use `CollectionError$inboundSchema` instead. */
  export const inboundSchema = CollectionError$inboundSchema;
  /** @deprecated use `CollectionError$outboundSchema` instead. */
  export const outboundSchema = CollectionError$outboundSchema;
  /** @deprecated use `CollectionError$Outbound` instead. */
  export type Outbound = CollectionError$Outbound;
}
