// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ErrorResponse - Error response returned for failed requests
type ErrorResponse struct {
	// Client-facing error message describing what went wrong
	Message  *string                 `json:"message,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
