/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientChatFilesUpload } from "../funcs/clientChatFilesUpload.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientChatFilesUploadMutationVariables = {
  uploadChatFilesRequest: components.UploadChatFilesRequest;
  timezoneOffset?: number | undefined;
  options?: RequestOptions;
};

export type ClientChatFilesUploadMutationData =
  components.UploadChatFilesResponse;

/**
 * Upload files for Chat.
 *
 * @remarks
 * Upload files for Chat.
 */
export function useClientChatFilesUploadMutation(
  options?: MutationHookOptions<
    ClientChatFilesUploadMutationData,
    Error,
    ClientChatFilesUploadMutationVariables
  >,
): UseMutationResult<
  ClientChatFilesUploadMutationData,
  Error,
  ClientChatFilesUploadMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientChatFilesUploadMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientChatFilesUpload(): MutationKey {
  return ["@gleanwork/api-client", "files", "upload"];
}

export function buildClientChatFilesUploadMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientChatFilesUploadMutationVariables,
  ) => Promise<ClientChatFilesUploadMutationData>;
} {
  return {
    mutationKey: mutationKeyClientChatFilesUpload(),
    mutationFn: function clientChatFilesUploadMutationFn({
      uploadChatFilesRequest,
      timezoneOffset,
      options,
    }): Promise<ClientChatFilesUploadMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientChatFilesUpload(
        client$,
        uploadChatFilesRequest,
        timezoneOffset,
        mergedOptions,
      ));
    },
  };
}
