/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientCollectionsAddItems } from "../funcs/clientCollectionsAddItems.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientCollectionsAddItemsMutationVariables = {
  addCollectionItemsRequest: components.AddCollectionItemsRequest;
  xGleanActAs?: string | undefined;
  xGleanAuthType?: string | undefined;
  options?: RequestOptions;
};

export type ClientCollectionsAddItemsMutationData =
  components.AddCollectionItemsResponse;

/**
 * Add Collection item
 *
 * @remarks
 * Add items to a Collection.
 */
export function useClientCollectionsAddItemsMutation(
  options?: MutationHookOptions<
    ClientCollectionsAddItemsMutationData,
    Error,
    ClientCollectionsAddItemsMutationVariables
  >,
): UseMutationResult<
  ClientCollectionsAddItemsMutationData,
  Error,
  ClientCollectionsAddItemsMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientCollectionsAddItemsMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientCollectionsAddItems(): MutationKey {
  return ["@gleanwork/api-client", "collections", "addItems"];
}

export function buildClientCollectionsAddItemsMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientCollectionsAddItemsMutationVariables,
  ) => Promise<ClientCollectionsAddItemsMutationData>;
} {
  return {
    mutationKey: mutationKeyClientCollectionsAddItems(),
    mutationFn: function clientCollectionsAddItemsMutationFn({
      addCollectionItemsRequest,
      xGleanActAs,
      xGleanAuthType,
      options,
    }): Promise<ClientCollectionsAddItemsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientCollectionsAddItems(
        client$,
        addCollectionItemsRequest,
        xGleanActAs,
        xGleanAuthType,
        mergedOptions,
      ));
    },
  };
}
