/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientAnnouncementsGet } from "../funcs/clientAnnouncementsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientAnnouncementsGetMutationVariables = {
  request: operations.GetannouncementRequest;
  options?: RequestOptions;
};

export type ClientAnnouncementsGetMutationData =
  components.GetAnnouncementResponse;

/**
 * Read Announcement
 *
 * @remarks
 * Read the details of an Announcement given its ID.
 */
export function useClientAnnouncementsGetMutation(
  options?: MutationHookOptions<
    ClientAnnouncementsGetMutationData,
    Error,
    ClientAnnouncementsGetMutationVariables
  >,
): UseMutationResult<
  ClientAnnouncementsGetMutationData,
  Error,
  ClientAnnouncementsGetMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientAnnouncementsGetMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientAnnouncementsGet(): MutationKey {
  return ["@gleanwork/api-client", "announcements", "get"];
}

export function buildClientAnnouncementsGetMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientAnnouncementsGetMutationVariables,
  ) => Promise<ClientAnnouncementsGetMutationData>;
} {
  return {
    mutationKey: mutationKeyClientAnnouncementsGet(),
    mutationFn: function clientAnnouncementsGetMutationFn({
      request,
      options,
    }): Promise<ClientAnnouncementsGetMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientAnnouncementsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
