/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientCollectionsRetrieve } from "../funcs/clientCollectionsRetrieve.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientCollectionsRetrieveMutationVariables = {
  request: components.GetCollectionRequest;
  options?: RequestOptions;
};

export type ClientCollectionsRetrieveMutationData =
  components.GetCollectionResponse;

/**
 * Read Collection
 *
 * @remarks
 * Read the details of a Collection given its ID. Does not fetch items in this Collection.
 */
export function useClientCollectionsRetrieveMutation(
  options?: MutationHookOptions<
    ClientCollectionsRetrieveMutationData,
    Error,
    ClientCollectionsRetrieveMutationVariables
  >,
): UseMutationResult<
  ClientCollectionsRetrieveMutationData,
  Error,
  ClientCollectionsRetrieveMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientCollectionsRetrieveMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientCollectionsRetrieve(): MutationKey {
  return ["@gleanwork/api-client", "collections", "retrieve"];
}

export function buildClientCollectionsRetrieveMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientCollectionsRetrieveMutationVariables,
  ) => Promise<ClientCollectionsRetrieveMutationData>;
} {
  return {
    mutationKey: mutationKeyClientCollectionsRetrieve(),
    mutationFn: function clientCollectionsRetrieveMutationFn({
      request,
      options,
    }): Promise<ClientCollectionsRetrieveMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientCollectionsRetrieve(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
