/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientChatDeleteFiles } from "../funcs/clientChatDeleteFiles.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientChatDeleteFilesMutationVariables = {
  deleteChatFilesRequest: components.DeleteChatFilesRequest;
  timezoneOffset?: number | undefined;
  options?: RequestOptions;
};

export type ClientChatDeleteFilesMutationData = void;

/**
 * Delete files uploaded by a user for chat.
 *
 * @remarks
 * Delete files uploaded by a user for Chat.
 */
export function useClientChatDeleteFilesMutation(
  options?: MutationHookOptions<
    ClientChatDeleteFilesMutationData,
    Error,
    ClientChatDeleteFilesMutationVariables
  >,
): UseMutationResult<
  ClientChatDeleteFilesMutationData,
  Error,
  ClientChatDeleteFilesMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientChatDeleteFilesMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientChatDeleteFiles(): MutationKey {
  return ["@gleanwork/api-client", "chat", "deleteFiles"];
}

export function buildClientChatDeleteFilesMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientChatDeleteFilesMutationVariables,
  ) => Promise<ClientChatDeleteFilesMutationData>;
} {
  return {
    mutationKey: mutationKeyClientChatDeleteFiles(),
    mutationFn: function clientChatDeleteFilesMutationFn({
      deleteChatFilesRequest,
      timezoneOffset,
      options,
    }): Promise<ClientChatDeleteFilesMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientChatDeleteFiles(
        client$,
        deleteChatFilesRequest,
        timezoneOffset,
        mergedOptions,
      ));
    },
  };
}
