/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientCollectionsEditItem } from "../funcs/clientCollectionsEditItem.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientCollectionsEditItemMutationVariables = {
  request: components.EditCollectionItemRequest;
  options?: RequestOptions;
};

export type ClientCollectionsEditItemMutationData =
  components.EditCollectionItemResponse;

/**
 * Update Collection item
 *
 * @remarks
 * Update the URL, Glean Document ID, description of an item within a Collection given its ID.
 */
export function useClientCollectionsEditItemMutation(
  options?: MutationHookOptions<
    ClientCollectionsEditItemMutationData,
    Error,
    ClientCollectionsEditItemMutationVariables
  >,
): UseMutationResult<
  ClientCollectionsEditItemMutationData,
  Error,
  ClientCollectionsEditItemMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientCollectionsEditItemMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientCollectionsEditItem(): MutationKey {
  return ["@gleanwork/api-client", "collections", "editItem"];
}

export function buildClientCollectionsEditItemMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientCollectionsEditItemMutationVariables,
  ) => Promise<ClientCollectionsEditItemMutationData>;
} {
  return {
    mutationKey: mutationKeyClientCollectionsEditItem(),
    mutationFn: function clientCollectionsEditItemMutationFn({
      request,
      options,
    }): Promise<ClientCollectionsEditItemMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientCollectionsEditItem(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
