/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientPinsRemove } from "../funcs/clientPinsRemove.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientPinsRemoveMutationVariables = {
  unpin: components.Unpin;
  xGleanActAs?: string | undefined;
  xGleanAuthType?: string | undefined;
  options?: RequestOptions;
};

export type ClientPinsRemoveMutationData = void;

/**
 * Delete pin
 *
 * @remarks
 * Unpin a previously pinned result.
 */
export function useClientPinsRemoveMutation(
  options?: MutationHookOptions<
    ClientPinsRemoveMutationData,
    Error,
    ClientPinsRemoveMutationVariables
  >,
): UseMutationResult<
  ClientPinsRemoveMutationData,
  Error,
  ClientPinsRemoveMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientPinsRemoveMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientPinsRemove(): MutationKey {
  return ["@gleanwork/api-client", "pins", "remove"];
}

export function buildClientPinsRemoveMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientPinsRemoveMutationVariables,
  ) => Promise<ClientPinsRemoveMutationData>;
} {
  return {
    mutationKey: mutationKeyClientPinsRemove(),
    mutationFn: function clientPinsRemoveMutationFn({
      unpin,
      xGleanActAs,
      xGleanAuthType,
      options,
    }): Promise<ClientPinsRemoveMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientPinsRemove(
        client$,
        unpin,
        xGleanActAs,
        xGleanAuthType,
        mergedOptions,
      ));
    },
  };
}
