/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientShortcutsList } from "../funcs/clientShortcutsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientShortcutsListMutationVariables = {
  request: operations.ListshortcutsRequest;
  options?: RequestOptions;
};

export type ClientShortcutsListMutationData =
  components.ListShortcutsPaginatedResponse;

/**
 * List shortcuts
 *
 * @remarks
 * List shortcuts editable/owned by the currently authenticated user.
 */
export function useClientShortcutsListMutation(
  options?: MutationHookOptions<
    ClientShortcutsListMutationData,
    Error,
    ClientShortcutsListMutationVariables
  >,
): UseMutationResult<
  ClientShortcutsListMutationData,
  Error,
  ClientShortcutsListMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientShortcutsListMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientShortcutsList(): MutationKey {
  return ["@gleanwork/api-client", "shortcuts", "list"];
}

export function buildClientShortcutsListMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientShortcutsListMutationVariables,
  ) => Promise<ClientShortcutsListMutationData>;
} {
  return {
    mutationKey: mutationKeyClientShortcutsList(),
    mutationFn: function clientShortcutsListMutationFn({
      request,
      options,
    }): Promise<ClientShortcutsListMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientShortcutsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
