/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { indexingPeopleIndexTeam } from "../funcs/indexingPeopleIndexTeam.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type IndexingPeopleIndexTeamMutationVariables = {
  request: components.IndexTeamRequest;
  options?: RequestOptions;
};

export type IndexingPeopleIndexTeamMutationData = void;

/**
 * Index team
 *
 * @remarks
 * Adds a team or updates information about a team
 */
export function useIndexingPeopleIndexTeamMutation(
  options?: MutationHookOptions<
    IndexingPeopleIndexTeamMutationData,
    Error,
    IndexingPeopleIndexTeamMutationVariables
  >,
): UseMutationResult<
  IndexingPeopleIndexTeamMutationData,
  Error,
  IndexingPeopleIndexTeamMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildIndexingPeopleIndexTeamMutation(client, options),
    ...options,
  });
}

export function mutationKeyIndexingPeopleIndexTeam(): MutationKey {
  return ["@gleanwork/api-client", "people", "indexTeam"];
}

export function buildIndexingPeopleIndexTeamMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: IndexingPeopleIndexTeamMutationVariables,
  ) => Promise<IndexingPeopleIndexTeamMutationData>;
} {
  return {
    mutationKey: mutationKeyIndexingPeopleIndexTeam(),
    mutationFn: function indexingPeopleIndexTeamMutationFn({
      request,
      options,
    }): Promise<IndexingPeopleIndexTeamMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(indexingPeopleIndexTeam(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
