/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it, test } from "vitest";
import { Glean } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

it.skip("People Post /Processallemployeesandteams", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step post_/processallemployeesandteams.test referencing operation post_/processallemployeesandteams not found in document`]",
  );
});

test("People Post /Api/index/v1 /Processallemployeesandteams", async () => {
  const testHttpClient = createTestHTTPClient(
    "post_/api/index/v1/processallemployeesandteams",
  );

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["GLEAN_BEARER_AUTH"] ?? "value",
  });

  await glean.indexing.people.processAllEmployeesAndTeams();
});
