/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Glean } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Summarize Summarize", async () => {
  const testHttpClient = createTestHTTPClient("summarize");

  const glean = new Glean({
    httpClient: testHttpClient,
    bearerAuth: process.env["GLEAN_BEARER_AUTH"] ?? "value",
  });

  const result = await glean.client.summarize.generate({
    summarizeRequest: {
      documentSpecs: [
        {},
        {},
      ],
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});
