/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Glean } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Tools Executeactiontool", async () => {
  const testHttpClient = createTestHTTPClient("executeactiontool");

  const glean = new Glean({
    httpClient: testHttpClient,
    bearerAuth: process.env["GLEAN_BEARER_AUTH"] ?? "value",
  });

  const result = await glean.client.tools.executeAction({
    executeActionToolRequest: {
      name: "<value>",
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});
