/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientActivityReport } from "../funcs/clientActivityReport.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activity extends ClientSDK {
  /**
   * Report document activity
   *
   * @remarks
   * Report user activity that occurs on indexed documents such as viewing or editing. This signal improves search quality.
   */
  async report(
    request: components.Activity,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(clientActivityReport(
      this,
      request,
      options,
    ));
  }
}
