/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientDocumentsGet } from "../funcs/clientDocumentsGet.js";
import { clientDocumentsGetAnalytics } from "../funcs/clientDocumentsGetAnalytics.js";
import { clientDocumentsGetByFacets } from "../funcs/clientDocumentsGetByFacets.js";
import { clientDocumentsGetPermissions } from "../funcs/clientDocumentsGetPermissions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ClientDocuments extends ClientSDK {
  /**
   * Read document permissions
   *
   * @remarks
   * Read the emails of all users who have access to the given document.
   */
  async getPermissions(
    request: operations.GetdocpermissionsRequest,
    options?: RequestOptions,
  ): Promise<components.GetDocPermissionsResponse> {
    return unwrapAsync(clientDocumentsGetPermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * Read documents
   *
   * @remarks
   * Read the documents including metadata (does not include enhanced metadata via `/documentmetadata`) for the given list of Glean Document IDs or URLs specified in the request.
   */
  async get(
    request: operations.GetdocumentsRequest,
    options?: RequestOptions,
  ): Promise<components.GetDocumentsResponse> {
    return unwrapAsync(clientDocumentsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Read documents by facets
   *
   * @remarks
   * Read the documents including metadata (does not include enhanced metadata via `/documentmetadata`) macthing the given facet conditions.
   */
  async getByFacets(
    request: operations.GetdocumentsbyfacetsRequest,
    options?: RequestOptions,
  ): Promise<components.GetDocumentsByFacetsResponse> {
    return unwrapAsync(clientDocumentsGetByFacets(
      this,
      request,
      options,
    ));
  }

  /**
   * Read document analytics
   *
   * @remarks
   * Read the document analytics information for the given list of Glean Document IDs or URLs specified in the request
   */
  async getAnalytics(
    request: operations.GetdocumentanalyticsRequest,
    options?: RequestOptions,
  ): Promise<components.GetDocumentAnalyticsResponse> {
    return unwrapAsync(clientDocumentsGetAnalytics(
      this,
      request,
      options,
    ));
  }
}
