/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { datasourcesGetDatasourceCredentialStatus } from "../funcs/datasourcesGetDatasourceCredentialStatus.js";
import { datasourcesGetDatasourceInstanceConfiguration } from "../funcs/datasourcesGetDatasourceInstanceConfiguration.js";
import { datasourcesRotateDatasourceCredentials } from "../funcs/datasourcesRotateDatasourceCredentials.js";
import { datasourcesUpdateDatasourceInstanceConfiguration } from "../funcs/datasourcesUpdateDatasourceInstanceConfiguration.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Datasources extends ClientSDK {
  /**
   * Get datasource instance configuration
   *
   * @remarks
   * Gets the greenlisted configuration values for a datasource instance. Returns only configuration keys that are exposed via the public API greenlist.
   */
  async getDatasourceInstanceConfiguration(
    datasourceId: string,
    instanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceConfigurationResponse> {
    return unwrapAsync(datasourcesGetDatasourceInstanceConfiguration(
      this,
      datasourceId,
      instanceId,
      options,
    ));
  }

  /**
   * Update datasource instance configuration
   *
   * @remarks
   * Updates the greenlisted configuration values for a datasource instance. Only configuration keys that are exposed via the public API greenlist may be set. Returns the full greenlisted configuration after the update is applied.
   */
  async updateDatasourceInstanceConfiguration(
    updateDatasourceConfigurationRequest:
      components.UpdateDatasourceConfigurationRequest,
    datasourceId: string,
    instanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceConfigurationResponse> {
    return unwrapAsync(datasourcesUpdateDatasourceInstanceConfiguration(
      this,
      updateDatasourceConfigurationRequest,
      datasourceId,
      instanceId,
      options,
    ));
  }

  /**
   * Get datasource instance credential status
   *
   * @remarks
   * Returns the current credential status for a datasource instance. Access is limited to callers with the ADMIN scope; the handler enforces this check.
   */
  async getDatasourceCredentialStatus(
    datasourceInstanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceCredentialStatusResponse> {
    return unwrapAsync(datasourcesGetDatasourceCredentialStatus(
      this,
      datasourceInstanceId,
      options,
    ));
  }

  /**
   * Rotate datasource instance credentials
   *
   * @remarks
   * Rotates the credentials that a datasource instance uses to connect to its upstream system. Replaces the active credential material with the supplied values and returns the credential status after rotation. Access is limited to callers with the ADMIN scope; the handler enforces this check.
   * Only keys recognized as credential material for the datasource type may be set in `credentials.values` (e.g. `clientSecret`, `apiToken`, `privateKey`, depending on the configured auth method). Unrecognized keys, or keys that correspond to non-credential configuration, cause a 400; other instance configuration must be updated via PATCH /configure/datasources/{datasourceId}/instances/{instanceId}.
   */
  async rotateDatasourceCredentials(
    rotateDatasourceCredentialsRequest:
      components.RotateDatasourceCredentialsRequest,
    datasourceInstanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceCredentialStatusResponse> {
    return unwrapAsync(datasourcesRotateDatasourceCredentials(
      this,
      rotateDatasourceCredentialsRequest,
      datasourceInstanceId,
      options,
    ));
  }
}
