/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { indexingDatasourcesAdd } from "../funcs/indexingDatasourcesAdd.js";
import { indexingDatasourcesGetConfig } from "../funcs/indexingDatasourcesGetConfig.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Datasources extends ClientSDK {
  /**
   * Add or update datasource
   *
   * @remarks
   * Add or update a custom datasource and its schema.
   */
  async add(
    request: components.CustomDatasourceConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(indexingDatasourcesAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * Get datasource config
   *
   * @remarks
   * Fetches the datasource config for the specified custom datasource.
   */
  async getConfig(
    request: components.GetDatasourceConfigRequest,
    options?: RequestOptions,
  ): Promise<components.CustomDatasourceConfig> {
    return unwrapAsync(indexingDatasourcesGetConfig(
      this,
      request,
      options,
    ));
  }
}
