/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientSearchAutocomplete } from "../funcs/clientSearchAutocomplete.js";
import { clientSearchQuery } from "../funcs/clientSearchQuery.js";
import { clientSearchQueryAsAdmin } from "../funcs/clientSearchQueryAsAdmin.js";
import { clientSearchRecommendations } from "../funcs/clientSearchRecommendations.js";
import { clientSearchRetrieveFeed } from "../funcs/clientSearchRetrieveFeed.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search the index (admin)
   *
   * @remarks
   * Retrieves results for search query without respect for permissions. This is available only to privileged users.
   */
  async queryAsAdmin(
    request?: components.SearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchResponse> {
    return unwrapAsync(clientSearchQueryAsAdmin(
      this,
      request,
      options,
    ));
  }

  /**
   * Autocomplete
   *
   * @remarks
   * Retrieve query suggestions, operators and documents for the given partially typed query.
   */
  async autocomplete(
    request: components.AutocompleteRequest,
    options?: RequestOptions,
  ): Promise<components.AutocompleteResponse> {
    return unwrapAsync(clientSearchAutocomplete(
      this,
      request,
      options,
    ));
  }

  /**
   * Feed of documents and events
   *
   * @remarks
   * The personalized feed/home includes different types of contents including suggestions, recents, calendar events and many more.
   */
  async retrieveFeed(
    request: components.FeedRequest,
    options?: RequestOptions,
  ): Promise<components.FeedResponse> {
    return unwrapAsync(clientSearchRetrieveFeed(
      this,
      request,
      options,
    ));
  }

  /**
   * Recommend documents
   *
   * @remarks
   * Retrieve recommended documents for the given URL or Glean Document ID.
   */
  async recommendations(
    request?: components.RecommendationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.ResultsResponse | undefined> {
    return unwrapAsync(clientSearchRecommendations(
      this,
      request,
      options,
    ));
  }

  /**
   * Search
   *
   * @remarks
   * Retrieve results from the index for the given query and filters.
   */
  async query(
    request?: components.SearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.SearchResponse> {
    return unwrapAsync(clientSearchQuery(
      this,
      request,
      options,
    ));
  }
}
