// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AddverificationreminderRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// Details about the reminder.
	ReminderRequest components.ReminderRequest `request:"mediaType=application/json"`
}

func (o *AddverificationreminderRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *AddverificationreminderRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *AddverificationreminderRequest) GetReminderRequest() components.ReminderRequest {
	if o == nil {
		return components.ReminderRequest{}
	}
	return o.ReminderRequest
}

type AddverificationreminderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Verification *components.Verification
}

func (o *AddverificationreminderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddverificationreminderResponse) GetVerification() *components.Verification {
	if o == nil {
		return nil
	}
	return o.Verification
}
