// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreatefindingsexportResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ExportInfo *components.ExportInfo
}

func (o *CreatefindingsexportResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatefindingsexportResponse) GetExportInfo() *components.ExportInfo {
	if o == nil {
		return nil
	}
	return o.ExportInfo
}
