// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeletecollectionRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// DeleteCollection request
	DeleteCollectionRequest components.DeleteCollectionRequest `request:"mediaType=application/json"`
}

func (o *DeletecollectionRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *DeletecollectionRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *DeletecollectionRequest) GetDeleteCollectionRequest() components.DeleteCollectionRequest {
	if o == nil {
		return components.DeleteCollectionRequest{}
	}
	return o.DeleteCollectionRequest
}

type DeletecollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeletecollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
