// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetchatfilesRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset      *int64                         `queryParam:"style=form,explode=true,name=timezoneOffset"`
	GetChatFilesRequest components.GetChatFilesRequest `request:"mediaType=application/json"`
}

func (o *GetchatfilesRequest) GetLocale() *string {
	if o == nil {
		return nil
	}
	return o.Locale
}

func (o *GetchatfilesRequest) GetTimezoneOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.TimezoneOffset
}

func (o *GetchatfilesRequest) GetGetChatFilesRequest() components.GetChatFilesRequest {
	if o == nil {
		return components.GetChatFilesRequest{}
	}
	return o.GetChatFilesRequest
}

type GetchatfilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetChatFilesResponse *components.GetChatFilesResponse
}

func (o *GetchatfilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetchatfilesResponse) GetGetChatFilesResponse() *components.GetChatFilesResponse {
	if o == nil {
		return nil
	}
	return o.GetChatFilesResponse
}
