// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetdocumentsbyfacetsRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// Information about facet conditions for documents to be retrieved.
	GetDocumentsByFacetsRequest *components.GetDocumentsByFacetsRequest `request:"mediaType=application/json"`
}

func (o *GetdocumentsbyfacetsRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *GetdocumentsbyfacetsRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *GetdocumentsbyfacetsRequest) GetGetDocumentsByFacetsRequest() *components.GetDocumentsByFacetsRequest {
	if o == nil {
		return nil
	}
	return o.GetDocumentsByFacetsRequest
}

type GetdocumentsbyfacetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetDocumentsByFacetsResponse *components.GetDocumentsByFacetsResponse
}

func (o *GetdocumentsbyfacetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetdocumentsbyfacetsResponse) GetGetDocumentsByFacetsResponse() *components.GetDocumentsByFacetsResponse {
	if o == nil {
		return nil
	}
	return o.GetDocumentsByFacetsResponse
}
