// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListpinsRequestBody - List pins request
type ListpinsRequestBody struct {
}

type ListpinsRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// List pins request
	RequestBody ListpinsRequestBody `request:"mediaType=application/json"`
}

func (o *ListpinsRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *ListpinsRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *ListpinsRequest) GetRequestBody() ListpinsRequestBody {
	if o == nil {
		return ListpinsRequestBody{}
	}
	return o.RequestBody
}

type ListpinsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListPinsResponse *components.ListPinsResponse
}

func (o *ListpinsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListpinsResponse) GetListPinsResponse() *components.ListPinsResponse {
	if o == nil {
		return nil
	}
	return o.ListPinsResponse
}
