// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ListanswersRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// ListAnswers request
	ListAnswersRequest components.ListAnswersRequest `request:"mediaType=application/json"`
}

func (o *ListanswersRequest) GetLocale() *string {
	if o == nil {
		return nil
	}
	return o.Locale
}

func (o *ListanswersRequest) GetListAnswersRequest() components.ListAnswersRequest {
	if o == nil {
		return components.ListAnswersRequest{}
	}
	return o.ListAnswersRequest
}

type ListanswersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListAnswersResponse *components.ListAnswersResponse
}

func (o *ListanswersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListanswersResponse) GetListAnswersResponse() *components.ListAnswersResponse {
	if o == nil {
		return nil
	}
	return o.ListAnswersResponse
}
