// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PinRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// Details about the document and query for the pin.
	PinRequest components.PinRequest `request:"mediaType=application/json"`
}

func (o *PinRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *PinRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *PinRequest) GetPinRequest() components.PinRequest {
	if o == nil {
		return components.PinRequest{}
	}
	return o.PinRequest
}

type PinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PinDocument *components.PinDocument
}

func (o *PinResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PinResponse) GetPinDocument() *components.PinDocument {
	if o == nil {
		return nil
	}
	return o.PinDocument
}
