// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PincollectionRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// PinCollection request
	PinCollectionRequest components.PinCollectionRequest `request:"mediaType=application/json"`
}

func (o *PincollectionRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *PincollectionRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *PincollectionRequest) GetPinCollectionRequest() components.PinCollectionRequest {
	if o == nil {
		return components.PinCollectionRequest{}
	}
	return o.PinCollectionRequest
}

type PincollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GetCollectionResponse *components.GetCollectionResponse
}

func (o *PincollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PincollectionResponse) GetGetCollectionResponse() *components.GetCollectionResponse {
	if o == nil {
		return nil
	}
	return o.GetCollectionResponse
}
