// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type RunagentRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset  *int64                     `queryParam:"style=form,explode=true,name=timezoneOffset"`
	RunAgentRequest components.RunAgentRequest `request:"mediaType=application/json"`
}

func (o *RunagentRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *RunagentRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *RunagentRequest) GetTimezoneOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.TimezoneOffset
}

func (o *RunagentRequest) GetRunAgentRequest() components.RunAgentRequest {
	if o == nil {
		return components.RunAgentRequest{}
	}
	return o.RunAgentRequest
}

type RunagentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ChatResponse *components.ChatResponse
}

func (o *RunagentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RunagentResponse) GetChatResponse() *components.ChatResponse {
	if o == nil {
		return nil
	}
	return o.ChatResponse
}
