// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UnpinRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// Details about the pin being unpinned.
	Unpin components.Unpin `request:"mediaType=application/json"`
}

func (o *UnpinRequest) GetLocale() *string {
	if o == nil {
		return nil
	}
	return o.Locale
}

func (o *UnpinRequest) GetUnpin() components.Unpin {
	if o == nil {
		return components.Unpin{}
	}
	return o.Unpin
}

type UnpinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *UnpinResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
