// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type VerifyRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XGleanActAs *string `header:"style=simple,explode=false,name=X-Glean-ActAs"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// Details about the verification request.
	VerifyRequest components.VerifyRequest `request:"mediaType=application/json"`
}

func (o *VerifyRequest) GetXGleanActAs() *string {
	if o == nil {
		return nil
	}
	return o.XGleanActAs
}

func (o *VerifyRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *VerifyRequest) GetVerifyRequest() components.VerifyRequest {
	if o == nil {
		return components.VerifyRequest{}
	}
	return o.VerifyRequest
}

type VerifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Verification *components.Verification
}

func (o *VerifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyResponse) GetVerification() *components.Verification {
	if o == nil {
		return nil
	}
	return o.Verification
}
