// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type VerifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Verification *components.Verification
}

func (o *VerifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyResponse) GetVerification() *components.Verification {
	if o == nil {
		return nil
	}
	return o.Verification
}
