/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateauthtokenRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xGleanActAs?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
};

/** @internal */
export const CreateauthtokenRequest$inboundSchema: z.ZodType<
  CreateauthtokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Glean-ActAs": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Glean-ActAs": "xGleanActAs",
    "X-Glean-Auth-Type": "xGleanAuthType",
  });
});

/** @internal */
export type CreateauthtokenRequest$Outbound = {
  "X-Glean-ActAs"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
};

/** @internal */
export const CreateauthtokenRequest$outboundSchema: z.ZodType<
  CreateauthtokenRequest$Outbound,
  z.ZodTypeDef,
  CreateauthtokenRequest
> = z.object({
  xGleanActAs: z.string().optional(),
  xGleanAuthType: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xGleanActAs: "X-Glean-ActAs",
    xGleanAuthType: "X-Glean-Auth-Type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateauthtokenRequest$ {
  /** @deprecated use `CreateauthtokenRequest$inboundSchema` instead. */
  export const inboundSchema = CreateauthtokenRequest$inboundSchema;
  /** @deprecated use `CreateauthtokenRequest$outboundSchema` instead. */
  export const outboundSchema = CreateauthtokenRequest$outboundSchema;
  /** @deprecated use `CreateauthtokenRequest$Outbound` instead. */
  export type Outbound = CreateauthtokenRequest$Outbound;
}

export function createauthtokenRequestToJSON(
  createauthtokenRequest: CreateauthtokenRequest,
): string {
  return JSON.stringify(
    CreateauthtokenRequest$outboundSchema.parse(createauthtokenRequest),
  );
}

export function createauthtokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateauthtokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateauthtokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateauthtokenRequest' from JSON`,
  );
}
