/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatecollectionRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xScioActas?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Collection content plus any additional metadata for the request.
   */
  createCollectionRequest: components.CreateCollectionRequest;
};

/** @internal */
export const CreatecollectionRequest$inboundSchema: z.ZodType<
  CreatecollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Scio-Actas": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  CreateCollectionRequest: components.CreateCollectionRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Scio-Actas": "xScioActas",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "CreateCollectionRequest": "createCollectionRequest",
  });
});

/** @internal */
export type CreatecollectionRequest$Outbound = {
  "X-Scio-Actas"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  CreateCollectionRequest: components.CreateCollectionRequest$Outbound;
};

/** @internal */
export const CreatecollectionRequest$outboundSchema: z.ZodType<
  CreatecollectionRequest$Outbound,
  z.ZodTypeDef,
  CreatecollectionRequest
> = z.object({
  xScioActas: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  createCollectionRequest: components.CreateCollectionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xScioActas: "X-Scio-Actas",
    xGleanAuthType: "X-Glean-Auth-Type",
    createCollectionRequest: "CreateCollectionRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatecollectionRequest$ {
  /** @deprecated use `CreatecollectionRequest$inboundSchema` instead. */
  export const inboundSchema = CreatecollectionRequest$inboundSchema;
  /** @deprecated use `CreatecollectionRequest$outboundSchema` instead. */
  export const outboundSchema = CreatecollectionRequest$outboundSchema;
  /** @deprecated use `CreatecollectionRequest$Outbound` instead. */
  export type Outbound = CreatecollectionRequest$Outbound;
}

export function createcollectionRequestToJSON(
  createcollectionRequest: CreatecollectionRequest,
): string {
  return JSON.stringify(
    CreatecollectionRequest$outboundSchema.parse(createcollectionRequest),
  );
}

export function createcollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreatecollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatecollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatecollectionRequest' from JSON`,
  );
}
