/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteanswerRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * DeleteAnswer request
   */
  deleteAnswerRequest: components.DeleteAnswerRequest;
};

/** @internal */
export const DeleteanswerRequest$inboundSchema: z.ZodType<
  DeleteanswerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  DeleteAnswerRequest: components.DeleteAnswerRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "DeleteAnswerRequest": "deleteAnswerRequest",
  });
});

/** @internal */
export type DeleteanswerRequest$Outbound = {
  locale?: string | undefined;
  DeleteAnswerRequest: components.DeleteAnswerRequest$Outbound;
};

/** @internal */
export const DeleteanswerRequest$outboundSchema: z.ZodType<
  DeleteanswerRequest$Outbound,
  z.ZodTypeDef,
  DeleteanswerRequest
> = z.object({
  locale: z.string().optional(),
  deleteAnswerRequest: components.DeleteAnswerRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deleteAnswerRequest: "DeleteAnswerRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteanswerRequest$ {
  /** @deprecated use `DeleteanswerRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteanswerRequest$inboundSchema;
  /** @deprecated use `DeleteanswerRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteanswerRequest$outboundSchema;
  /** @deprecated use `DeleteanswerRequest$Outbound` instead. */
  export type Outbound = DeleteanswerRequest$Outbound;
}

export function deleteanswerRequestToJSON(
  deleteanswerRequest: DeleteanswerRequest,
): string {
  return JSON.stringify(
    DeleteanswerRequest$outboundSchema.parse(deleteanswerRequest),
  );
}

export function deleteanswerRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteanswerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteanswerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteanswerRequest' from JSON`,
  );
}
