/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FeedRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xScioActas?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Includes request params, client data and more for making user's feed.
   */
  feedRequest: components.FeedRequest;
};

/** @internal */
export const FeedRequest$inboundSchema: z.ZodType<
  FeedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Scio-Actas": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  FeedRequest: components.FeedRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Scio-Actas": "xScioActas",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "FeedRequest": "feedRequest",
  });
});

/** @internal */
export type FeedRequest$Outbound = {
  "X-Scio-Actas"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  FeedRequest: components.FeedRequest$Outbound;
};

/** @internal */
export const FeedRequest$outboundSchema: z.ZodType<
  FeedRequest$Outbound,
  z.ZodTypeDef,
  FeedRequest
> = z.object({
  xScioActas: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  feedRequest: components.FeedRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xScioActas: "X-Scio-Actas",
    xGleanAuthType: "X-Glean-Auth-Type",
    feedRequest: "FeedRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FeedRequest$ {
  /** @deprecated use `FeedRequest$inboundSchema` instead. */
  export const inboundSchema = FeedRequest$inboundSchema;
  /** @deprecated use `FeedRequest$outboundSchema` instead. */
  export const outboundSchema = FeedRequest$outboundSchema;
  /** @deprecated use `FeedRequest$Outbound` instead. */
  export type Outbound = FeedRequest$Outbound;
}

export function feedRequestToJSON(feedRequest: FeedRequest): string {
  return JSON.stringify(FeedRequest$outboundSchema.parse(feedRequest));
}

export function feedRequestFromJSON(
  jsonString: string,
): SafeParseResult<FeedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeedRequest' from JSON`,
  );
}
