/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetdocumentsbyfacetsRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Information about facet conditions for documents to be retrieved.
   */
  getDocumentsByFacetsRequest?:
    | components.GetDocumentsByFacetsRequest
    | undefined;
};

/** @internal */
export const GetdocumentsbyfacetsRequest$inboundSchema: z.ZodType<
  GetdocumentsbyfacetsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  GetDocumentsByFacetsRequest: components
    .GetDocumentsByFacetsRequest$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "GetDocumentsByFacetsRequest": "getDocumentsByFacetsRequest",
  });
});

/** @internal */
export type GetdocumentsbyfacetsRequest$Outbound = {
  locale?: string | undefined;
  GetDocumentsByFacetsRequest?:
    | components.GetDocumentsByFacetsRequest$Outbound
    | undefined;
};

/** @internal */
export const GetdocumentsbyfacetsRequest$outboundSchema: z.ZodType<
  GetdocumentsbyfacetsRequest$Outbound,
  z.ZodTypeDef,
  GetdocumentsbyfacetsRequest
> = z.object({
  locale: z.string().optional(),
  getDocumentsByFacetsRequest: components
    .GetDocumentsByFacetsRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    getDocumentsByFacetsRequest: "GetDocumentsByFacetsRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetdocumentsbyfacetsRequest$ {
  /** @deprecated use `GetdocumentsbyfacetsRequest$inboundSchema` instead. */
  export const inboundSchema = GetdocumentsbyfacetsRequest$inboundSchema;
  /** @deprecated use `GetdocumentsbyfacetsRequest$outboundSchema` instead. */
  export const outboundSchema = GetdocumentsbyfacetsRequest$outboundSchema;
  /** @deprecated use `GetdocumentsbyfacetsRequest$Outbound` instead. */
  export type Outbound = GetdocumentsbyfacetsRequest$Outbound;
}

export function getdocumentsbyfacetsRequestToJSON(
  getdocumentsbyfacetsRequest: GetdocumentsbyfacetsRequest,
): string {
  return JSON.stringify(
    GetdocumentsbyfacetsRequest$outboundSchema.parse(
      getdocumentsbyfacetsRequest,
    ),
  );
}

export function getdocumentsbyfacetsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetdocumentsbyfacetsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetdocumentsbyfacetsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetdocumentsbyfacetsRequest' from JSON`,
  );
}
