/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetshortcutRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * GetShortcut request
   */
  getShortcutRequest: components.GetShortcutRequestUnion;
};

/** @internal */
export const GetshortcutRequest$inboundSchema: z.ZodType<
  GetshortcutRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  GetShortcutRequest: components.GetShortcutRequestUnion$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "GetShortcutRequest": "getShortcutRequest",
  });
});

/** @internal */
export type GetshortcutRequest$Outbound = {
  locale?: string | undefined;
  GetShortcutRequest: components.GetShortcutRequestUnion$Outbound;
};

/** @internal */
export const GetshortcutRequest$outboundSchema: z.ZodType<
  GetshortcutRequest$Outbound,
  z.ZodTypeDef,
  GetshortcutRequest
> = z.object({
  locale: z.string().optional(),
  getShortcutRequest: components.GetShortcutRequestUnion$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    getShortcutRequest: "GetShortcutRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetshortcutRequest$ {
  /** @deprecated use `GetshortcutRequest$inboundSchema` instead. */
  export const inboundSchema = GetshortcutRequest$inboundSchema;
  /** @deprecated use `GetshortcutRequest$outboundSchema` instead. */
  export const outboundSchema = GetshortcutRequest$outboundSchema;
  /** @deprecated use `GetshortcutRequest$Outbound` instead. */
  export type Outbound = GetshortcutRequest$Outbound;
}

export function getshortcutRequestToJSON(
  getshortcutRequest: GetshortcutRequest,
): string {
  return JSON.stringify(
    GetshortcutRequest$outboundSchema.parse(getshortcutRequest),
  );
}

export function getshortcutRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetshortcutRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetshortcutRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetshortcutRequest' from JSON`,
  );
}
