/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InsightsRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xGleanActAs?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Includes request params for insights dashboard data.
   */
  insightsRequest: components.InsightsRequest;
};

/** @internal */
export const InsightsRequest$inboundSchema: z.ZodType<
  InsightsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Glean-ActAs": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  InsightsRequest: components.InsightsRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Glean-ActAs": "xGleanActAs",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "InsightsRequest": "insightsRequest",
  });
});

/** @internal */
export type InsightsRequest$Outbound = {
  "X-Glean-ActAs"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  InsightsRequest: components.InsightsRequest$Outbound;
};

/** @internal */
export const InsightsRequest$outboundSchema: z.ZodType<
  InsightsRequest$Outbound,
  z.ZodTypeDef,
  InsightsRequest
> = z.object({
  xGleanActAs: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  insightsRequest: components.InsightsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xGleanActAs: "X-Glean-ActAs",
    xGleanAuthType: "X-Glean-Auth-Type",
    insightsRequest: "InsightsRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsightsRequest$ {
  /** @deprecated use `InsightsRequest$inboundSchema` instead. */
  export const inboundSchema = InsightsRequest$inboundSchema;
  /** @deprecated use `InsightsRequest$outboundSchema` instead. */
  export const outboundSchema = InsightsRequest$outboundSchema;
  /** @deprecated use `InsightsRequest$Outbound` instead. */
  export type Outbound = InsightsRequest$Outbound;
}

export function insightsRequestToJSON(
  insightsRequest: InsightsRequest,
): string {
  return JSON.stringify(InsightsRequest$outboundSchema.parse(insightsRequest));
}

export function insightsRequestFromJSON(
  jsonString: string,
): SafeParseResult<InsightsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsightsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsightsRequest' from JSON`,
  );
}
