/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListentitiesRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xScioActas?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * List people request
   */
  listEntitiesRequest: components.ListEntitiesRequest;
};

/** @internal */
export const ListentitiesRequest$inboundSchema: z.ZodType<
  ListentitiesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Scio-Actas": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  ListEntitiesRequest: components.ListEntitiesRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Scio-Actas": "xScioActas",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "ListEntitiesRequest": "listEntitiesRequest",
  });
});

/** @internal */
export type ListentitiesRequest$Outbound = {
  "X-Scio-Actas"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  ListEntitiesRequest: components.ListEntitiesRequest$Outbound;
};

/** @internal */
export const ListentitiesRequest$outboundSchema: z.ZodType<
  ListentitiesRequest$Outbound,
  z.ZodTypeDef,
  ListentitiesRequest
> = z.object({
  xScioActas: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  listEntitiesRequest: components.ListEntitiesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xScioActas: "X-Scio-Actas",
    xGleanAuthType: "X-Glean-Auth-Type",
    listEntitiesRequest: "ListEntitiesRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListentitiesRequest$ {
  /** @deprecated use `ListentitiesRequest$inboundSchema` instead. */
  export const inboundSchema = ListentitiesRequest$inboundSchema;
  /** @deprecated use `ListentitiesRequest$outboundSchema` instead. */
  export const outboundSchema = ListentitiesRequest$outboundSchema;
  /** @deprecated use `ListentitiesRequest$Outbound` instead. */
  export type Outbound = ListentitiesRequest$Outbound;
}

export function listentitiesRequestToJSON(
  listentitiesRequest: ListentitiesRequest,
): string {
  return JSON.stringify(
    ListentitiesRequest$outboundSchema.parse(listentitiesRequest),
  );
}

export function listentitiesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListentitiesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListentitiesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListentitiesRequest' from JSON`,
  );
}
