/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PreviewanswerRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xGleanActAs?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * PreviewAnswer request
   */
  structuredTextMutableProperties: components.StructuredTextMutableProperties;
};

/** @internal */
export const PreviewanswerRequest$inboundSchema: z.ZodType<
  PreviewanswerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Glean-ActAs": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  StructuredTextMutableProperties:
    components.StructuredTextMutableProperties$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Glean-ActAs": "xGleanActAs",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "StructuredTextMutableProperties": "structuredTextMutableProperties",
  });
});

/** @internal */
export type PreviewanswerRequest$Outbound = {
  "X-Glean-ActAs"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  StructuredTextMutableProperties:
    components.StructuredTextMutableProperties$Outbound;
};

/** @internal */
export const PreviewanswerRequest$outboundSchema: z.ZodType<
  PreviewanswerRequest$Outbound,
  z.ZodTypeDef,
  PreviewanswerRequest
> = z.object({
  xGleanActAs: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  structuredTextMutableProperties:
    components.StructuredTextMutableProperties$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xGleanActAs: "X-Glean-ActAs",
    xGleanAuthType: "X-Glean-Auth-Type",
    structuredTextMutableProperties: "StructuredTextMutableProperties",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreviewanswerRequest$ {
  /** @deprecated use `PreviewanswerRequest$inboundSchema` instead. */
  export const inboundSchema = PreviewanswerRequest$inboundSchema;
  /** @deprecated use `PreviewanswerRequest$outboundSchema` instead. */
  export const outboundSchema = PreviewanswerRequest$outboundSchema;
  /** @deprecated use `PreviewanswerRequest$Outbound` instead. */
  export type Outbound = PreviewanswerRequest$Outbound;
}

export function previewanswerRequestToJSON(
  previewanswerRequest: PreviewanswerRequest,
): string {
  return JSON.stringify(
    PreviewanswerRequest$outboundSchema.parse(previewanswerRequest),
  );
}

export function previewanswerRequestFromJSON(
  jsonString: string,
): SafeParseResult<PreviewanswerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewanswerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewanswerRequest' from JSON`,
  );
}
