/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PublicconfigRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xGleanActAs?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Public Config request
   */
  publicConfigRequest?: components.PublicConfigRequest | undefined;
};

/** @internal */
export const PublicconfigRequest$inboundSchema: z.ZodType<
  PublicconfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Glean-ActAs": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  PublicConfigRequest: components.PublicConfigRequest$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "X-Glean-ActAs": "xGleanActAs",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "PublicConfigRequest": "publicConfigRequest",
  });
});

/** @internal */
export type PublicconfigRequest$Outbound = {
  "X-Glean-ActAs"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  PublicConfigRequest?: components.PublicConfigRequest$Outbound | undefined;
};

/** @internal */
export const PublicconfigRequest$outboundSchema: z.ZodType<
  PublicconfigRequest$Outbound,
  z.ZodTypeDef,
  PublicconfigRequest
> = z.object({
  xGleanActAs: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  publicConfigRequest: components.PublicConfigRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    xGleanActAs: "X-Glean-ActAs",
    xGleanAuthType: "X-Glean-Auth-Type",
    publicConfigRequest: "PublicConfigRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PublicconfigRequest$ {
  /** @deprecated use `PublicconfigRequest$inboundSchema` instead. */
  export const inboundSchema = PublicconfigRequest$inboundSchema;
  /** @deprecated use `PublicconfigRequest$outboundSchema` instead. */
  export const outboundSchema = PublicconfigRequest$outboundSchema;
  /** @deprecated use `PublicconfigRequest$Outbound` instead. */
  export type Outbound = PublicconfigRequest$Outbound;
}

export function publicconfigRequestToJSON(
  publicconfigRequest: PublicconfigRequest,
): string {
  return JSON.stringify(
    PublicconfigRequest$outboundSchema.parse(publicconfigRequest),
  );
}

export function publicconfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<PublicconfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicconfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicconfigRequest' from JSON`,
  );
}
