/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemovecredentialRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xScioActas?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Credential content
   */
  removeCredentialRequest: components.RemoveCredentialRequest;
};

/** @internal */
export const RemovecredentialRequest$inboundSchema: z.ZodType<
  RemovecredentialRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Scio-Actas": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  RemoveCredentialRequest: components.RemoveCredentialRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Scio-Actas": "xScioActas",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "RemoveCredentialRequest": "removeCredentialRequest",
  });
});

/** @internal */
export type RemovecredentialRequest$Outbound = {
  "X-Scio-Actas"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  RemoveCredentialRequest: components.RemoveCredentialRequest$Outbound;
};

/** @internal */
export const RemovecredentialRequest$outboundSchema: z.ZodType<
  RemovecredentialRequest$Outbound,
  z.ZodTypeDef,
  RemovecredentialRequest
> = z.object({
  xScioActas: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  removeCredentialRequest: components.RemoveCredentialRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xScioActas: "X-Scio-Actas",
    xGleanAuthType: "X-Glean-Auth-Type",
    removeCredentialRequest: "RemoveCredentialRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemovecredentialRequest$ {
  /** @deprecated use `RemovecredentialRequest$inboundSchema` instead. */
  export const inboundSchema = RemovecredentialRequest$inboundSchema;
  /** @deprecated use `RemovecredentialRequest$outboundSchema` instead. */
  export const outboundSchema = RemovecredentialRequest$outboundSchema;
  /** @deprecated use `RemovecredentialRequest$Outbound` instead. */
  export type Outbound = RemovecredentialRequest$Outbound;
}

export function removecredentialRequestToJSON(
  removecredentialRequest: RemovecredentialRequest,
): string {
  return JSON.stringify(
    RemovecredentialRequest$outboundSchema.parse(removecredentialRequest),
  );
}

export function removecredentialRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemovecredentialRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemovecredentialRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemovecredentialRequest' from JSON`,
  );
}
