/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateshortcutRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Shortcut content. Id need to be specified for the shortcut.
   */
  updateShortcutRequest: components.UpdateShortcutRequest;
};

/** @internal */
export const UpdateshortcutRequest$inboundSchema: z.ZodType<
  UpdateshortcutRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  UpdateShortcutRequest: components.UpdateShortcutRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateShortcutRequest": "updateShortcutRequest",
  });
});

/** @internal */
export type UpdateshortcutRequest$Outbound = {
  locale?: string | undefined;
  UpdateShortcutRequest: components.UpdateShortcutRequest$Outbound;
};

/** @internal */
export const UpdateshortcutRequest$outboundSchema: z.ZodType<
  UpdateshortcutRequest$Outbound,
  z.ZodTypeDef,
  UpdateshortcutRequest
> = z.object({
  locale: z.string().optional(),
  updateShortcutRequest: components.UpdateShortcutRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateShortcutRequest: "UpdateShortcutRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateshortcutRequest$ {
  /** @deprecated use `UpdateshortcutRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateshortcutRequest$inboundSchema;
  /** @deprecated use `UpdateshortcutRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateshortcutRequest$outboundSchema;
  /** @deprecated use `UpdateshortcutRequest$Outbound` instead. */
  export type Outbound = UpdateshortcutRequest$Outbound;
}

export function updateshortcutRequestToJSON(
  updateshortcutRequest: UpdateshortcutRequest,
): string {
  return JSON.stringify(
    UpdateshortcutRequest$outboundSchema.parse(updateshortcutRequest),
  );
}

export function updateshortcutRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateshortcutRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateshortcutRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateshortcutRequest' from JSON`,
  );
}
