/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateannouncementRequest = {
  /**
   * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
   */
  xScioActas?: string | undefined;
  /**
   * Auth type being used to access the endpoint (should be non-empty only for global tokens).
   */
  xGleanAuthType?: string | undefined;
  /**
   * Announcement content. Id need to be specified for the announcement.
   */
  updateAnnouncementRequest: components.UpdateAnnouncementRequest;
};

/** @internal */
export const UpdateannouncementRequest$inboundSchema: z.ZodType<
  UpdateannouncementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Scio-Actas": z.string().optional(),
  "X-Glean-Auth-Type": z.string().optional(),
  UpdateAnnouncementRequest: components.UpdateAnnouncementRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Scio-Actas": "xScioActas",
    "X-Glean-Auth-Type": "xGleanAuthType",
    "UpdateAnnouncementRequest": "updateAnnouncementRequest",
  });
});

/** @internal */
export type UpdateannouncementRequest$Outbound = {
  "X-Scio-Actas"?: string | undefined;
  "X-Glean-Auth-Type"?: string | undefined;
  UpdateAnnouncementRequest: components.UpdateAnnouncementRequest$Outbound;
};

/** @internal */
export const UpdateannouncementRequest$outboundSchema: z.ZodType<
  UpdateannouncementRequest$Outbound,
  z.ZodTypeDef,
  UpdateannouncementRequest
> = z.object({
  xScioActas: z.string().optional(),
  xGleanAuthType: z.string().optional(),
  updateAnnouncementRequest:
    components.UpdateAnnouncementRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xScioActas: "X-Scio-Actas",
    xGleanAuthType: "X-Glean-Auth-Type",
    updateAnnouncementRequest: "UpdateAnnouncementRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateannouncementRequest$ {
  /** @deprecated use `UpdateannouncementRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateannouncementRequest$inboundSchema;
  /** @deprecated use `UpdateannouncementRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateannouncementRequest$outboundSchema;
  /** @deprecated use `UpdateannouncementRequest$Outbound` instead. */
  export type Outbound = UpdateannouncementRequest$Outbound;
}

export function updateannouncementRequestToJSON(
  updateannouncementRequest: UpdateannouncementRequest,
): string {
  return JSON.stringify(
    UpdateannouncementRequest$outboundSchema.parse(updateannouncementRequest),
  );
}

export function updateannouncementRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateannouncementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateannouncementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateannouncementRequest' from JSON`,
  );
}
