/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateannouncementRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Announcement content. Id need to be specified for the announcement.
   */
  updateAnnouncementRequest: components.UpdateAnnouncementRequest;
};

/** @internal */
export const UpdateannouncementRequest$inboundSchema: z.ZodType<
  UpdateannouncementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  UpdateAnnouncementRequest: components.UpdateAnnouncementRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateAnnouncementRequest": "updateAnnouncementRequest",
  });
});

/** @internal */
export type UpdateannouncementRequest$Outbound = {
  locale?: string | undefined;
  UpdateAnnouncementRequest: components.UpdateAnnouncementRequest$Outbound;
};

/** @internal */
export const UpdateannouncementRequest$outboundSchema: z.ZodType<
  UpdateannouncementRequest$Outbound,
  z.ZodTypeDef,
  UpdateannouncementRequest
> = z.object({
  locale: z.string().optional(),
  updateAnnouncementRequest:
    components.UpdateAnnouncementRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateAnnouncementRequest: "UpdateAnnouncementRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateannouncementRequest$ {
  /** @deprecated use `UpdateannouncementRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateannouncementRequest$inboundSchema;
  /** @deprecated use `UpdateannouncementRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateannouncementRequest$outboundSchema;
  /** @deprecated use `UpdateannouncementRequest$Outbound` instead. */
  export type Outbound = UpdateannouncementRequest$Outbound;
}

export function updateannouncementRequestToJSON(
  updateannouncementRequest: UpdateannouncementRequest,
): string {
  return JSON.stringify(
    UpdateannouncementRequest$outboundSchema.parse(updateannouncementRequest),
  );
}

export function updateannouncementRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateannouncementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateannouncementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateannouncementRequest' from JSON`,
  );
}
