/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VerifyRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Details about the verification request.
   */
  verifyRequest: components.VerifyRequest;
};

/** @internal */
export const VerifyRequest$inboundSchema: z.ZodType<
  VerifyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  locale: z.string().optional(),
  VerifyRequest: components.VerifyRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "VerifyRequest": "verifyRequest",
  });
});

/** @internal */
export type VerifyRequest$Outbound = {
  locale?: string | undefined;
  VerifyRequest: components.VerifyRequest$Outbound;
};

/** @internal */
export const VerifyRequest$outboundSchema: z.ZodType<
  VerifyRequest$Outbound,
  z.ZodTypeDef,
  VerifyRequest
> = z.object({
  locale: z.string().optional(),
  verifyRequest: components.VerifyRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    verifyRequest: "VerifyRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VerifyRequest$ {
  /** @deprecated use `VerifyRequest$inboundSchema` instead. */
  export const inboundSchema = VerifyRequest$inboundSchema;
  /** @deprecated use `VerifyRequest$outboundSchema` instead. */
  export const outboundSchema = VerifyRequest$outboundSchema;
  /** @deprecated use `VerifyRequest$Outbound` instead. */
  export type Outbound = VerifyRequest$Outbound;
}

export function verifyRequestToJSON(verifyRequest: VerifyRequest): string {
  return JSON.stringify(VerifyRequest$outboundSchema.parse(verifyRequest));
}

export function verifyRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerifyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyRequest' from JSON`,
  );
}
