// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// AuthStatus - The per-user authorization status for a datasource.
type AuthStatus string

const (
	AuthStatusDisabled     AuthStatus = "DISABLED"
	AuthStatusAwaitingAuth AuthStatus = "AWAITING_AUTH"
	AuthStatusAuthorized   AuthStatus = "AUTHORIZED"
	AuthStatusStaleOauth   AuthStatus = "STALE_OAUTH"
	AuthStatusSegMigration AuthStatus = "SEG_MIGRATION"
)

func (e AuthStatus) ToPointer() *AuthStatus {
	return &e
}
func (e *AuthStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DISABLED":
		fallthrough
	case "AWAITING_AUTH":
		fallthrough
	case "AUTHORIZED":
		fallthrough
	case "STALE_OAUTH":
		fallthrough
	case "SEG_MIGRATION":
		*e = AuthStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthStatus: %v", v)
	}
}
