// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BulkIndexShortcutsRequest - Describes the request body of the /bulkindexshortcuts API call
type BulkIndexShortcutsRequest struct {
	// Unique id that must be used for this bulk upload instance
	UploadID string `json:"uploadId"`
	// true if this is the first page of the upload. Defaults to false
	IsFirstPage *bool `json:"isFirstPage,omitempty"`
	// true if this is the last page of the upload. Defaults to false
	IsLastPage *bool `json:"isLastPage,omitempty"`
	// Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
	ForceRestartUpload *bool `json:"forceRestartUpload,omitempty"`
	// Batch of shortcuts information
	Shortcuts []ExternalShortcut `json:"shortcuts"`
}

func (o *BulkIndexShortcutsRequest) GetUploadID() string {
	if o == nil {
		return ""
	}
	return o.UploadID
}

func (o *BulkIndexShortcutsRequest) GetIsFirstPage() *bool {
	if o == nil {
		return nil
	}
	return o.IsFirstPage
}

func (o *BulkIndexShortcutsRequest) GetIsLastPage() *bool {
	if o == nil {
		return nil
	}
	return o.IsLastPage
}

func (o *BulkIndexShortcutsRequest) GetForceRestartUpload() *bool {
	if o == nil {
		return nil
	}
	return o.ForceRestartUpload
}

func (o *BulkIndexShortcutsRequest) GetShortcuts() []ExternalShortcut {
	if o == nil {
		return []ExternalShortcut{}
	}
	return o.Shortcuts
}
