// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConfigurationValue - A single configuration value, either a scalar or a list
type ConfigurationValue struct {
	// The configuration value as a string. Only one of value or valueList should be populated.
	Value *string `json:"value,omitempty"`
	// The configuration value as a list of strings. Only one of value or valueList should be populated.
	ValueList []string `json:"valueList,omitempty"`
}

func (o *ConfigurationValue) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *ConfigurationValue) GetValueList() []string {
	if o == nil {
		return nil
	}
	return o.ValueList
}
