// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type CustomFieldData struct {
	// A user-facing label for this field.
	Label  string             `json:"label"`
	Values []CustomFieldValue `json:"values"`
	// Determines whether the client should display this custom field
	Displayable *bool `default:"true" json:"displayable"`
}

func (c CustomFieldData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomFieldData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CustomFieldData) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *CustomFieldData) GetValues() []CustomFieldValue {
	if o == nil {
		return []CustomFieldValue{}
	}
	return o.Values
}

func (o *CustomFieldData) GetDisplayable() *bool {
	if o == nil {
		return nil
	}
	return o.Displayable
}
