// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomSensitiveExpression struct {
	// Identifier for the custom sensitive expression.
	ID      *string              `json:"id,omitempty"`
	Keyword *CustomSensitiveRule `json:"keyword,omitempty"`
	// The expression to evaluate the keyword match.
	EvaluationExpression *string `json:"evaluationExpression,omitempty"`
}

func (o *CustomSensitiveExpression) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CustomSensitiveExpression) GetKeyword() *CustomSensitiveRule {
	if o == nil {
		return nil
	}
	return o.Keyword
}

func (o *CustomSensitiveExpression) GetEvaluationExpression() *string {
	if o == nil {
		return nil
	}
	return o.EvaluationExpression
}
