// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DatasourceObjectTypeDocumentCountEntry struct {
	// The object type of the document
	ObjectType *string `json:"objectType,omitempty"`
	// The number of documents of the corresponding objectType
	Count *int64 `json:"count,omitempty"`
}

func (o *DatasourceObjectTypeDocumentCountEntry) GetObjectType() *string {
	if o == nil {
		return nil
	}
	return o.ObjectType
}

func (o *DatasourceObjectTypeDocumentCountEntry) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}
