// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DatasourceGroupDefinition - describes a group in the datasource
type DatasourceGroupDefinition struct {
	// name of the group. Should be unique among all groups for the datasource, and cannot have spaces.
	Name string `json:"name"`
}

func (o *DatasourceGroupDefinition) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
