// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DebugDocumentsResponseItem - Describes the response body of a single document in the /debug/{datasource}/documents API call
type DebugDocumentsResponseItem struct {
	// Id of the document
	DocID *string `json:"docId,omitempty"`
	// objectType of the document
	ObjectType *string `json:"objectType,omitempty"`
	// Describes the response body of the /debug/{datasource}/document API call
	DebugInfo *DebugDocumentResponse `json:"debugInfo,omitempty"`
}

func (o *DebugDocumentsResponseItem) GetDocID() *string {
	if o == nil {
		return nil
	}
	return o.DocID
}

func (o *DebugDocumentsResponseItem) GetObjectType() *string {
	if o == nil {
		return nil
	}
	return o.ObjectType
}

func (o *DebugDocumentsResponseItem) GetDebugInfo() *DebugDocumentResponse {
	if o == nil {
		return nil
	}
	return o.DebugInfo
}
