// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteQueryHistoryResponse struct {
	Error *DeleteQueryHistoryError `json:"error,omitempty"`
}

func (o *DeleteQueryHistoryResponse) GetError() *DeleteQueryHistoryError {
	if o == nil {
		return nil
	}
	return o.Error
}
