// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteAnswerRequest struct {
	// The opaque ID of the Answer.
	ID int64 `json:"id"`
	// Glean Document ID of the Answer. The Glean Document ID is supported for cases where the Answer ID isn't available. If both are available, using the Answer ID is preferred.
	DocID *string `json:"docId,omitempty"`
}

func (o *DeleteAnswerRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *DeleteAnswerRequest) GetDocID() *string {
	if o == nil {
		return nil
	}
	return o.DocID
}
