// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DocumentSection struct {
	// The title of the document section (e.g. the section header).
	Title *string `json:"title,omitempty"`
	// The permalink of the document section.
	URL *string `json:"url,omitempty"`
}

func (o *DocumentSection) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *DocumentSection) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
