// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EditPinRequest struct {
	// The query strings for which the pinned result will show.
	Queries []string `json:"queries,omitempty"`
	// Filters which restrict who should see the pinned document. Values are taken from the corresponding filters in people search.
	AudienceFilters []FacetFilter `json:"audienceFilters,omitempty"`
	// The opaque id of the pin to be edited.
	ID *string `json:"id,omitempty"`
}

func (o *EditPinRequest) GetQueries() []string {
	if o == nil {
		return nil
	}
	return o.Queries
}

func (o *EditPinRequest) GetAudienceFilters() []FacetFilter {
	if o == nil {
		return nil
	}
	return o.AudienceFilters
}

func (o *EditPinRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
