// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// EntityType - The type of entity.
type EntityType string

const (
	EntityTypePerson   EntityType = "PERSON"
	EntityTypeProject  EntityType = "PROJECT"
	EntityTypeCustomer EntityType = "CUSTOMER"
)

func (e EntityType) ToPointer() *EntityType {
	return &e
}
func (e *EntityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PERSON":
		fallthrough
	case "PROJECT":
		fallthrough
	case "CUSTOMER":
		*e = EntityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityType: %v", v)
	}
}
