// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EntityRelationship - Describes a relationship edge between a source and destination entity
type EntityRelationship struct {
	// The title or type of relationship. Currently an enum of `CHIEF_OF_STAFF`, `EXECUTIVE_ASSISTANT`
	Name string `json:"name"`
	// Email of the person with whom the relationship exists. Per the example above, either `B` or `C`'s email depending on the relationship.
	Email string `json:"email"`
}

func (o *EntityRelationship) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EntityRelationship) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}
