// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetEventsResponse struct {
	// The requested events. Uses a FeedResult for now as a Calendar Event doesn't have all event info such as attachments.
	Events []FeedResult `json:"events,omitempty"`
}

func (o *GetEventsResponse) GetEvents() []FeedResult {
	if o == nil {
		return nil
	}
	return o.Events
}
