// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IndexEmployeeListRequest - Describes the request body of the /indexemployeelist API call
type IndexEmployeeListRequest struct {
	// List of employee info and version.
	Employees []IndexEmployeeRequest `json:"employees,omitempty"`
}

func (o *IndexEmployeeListRequest) GetEmployees() []IndexEmployeeRequest {
	if o == nil {
		return nil
	}
	return o.Employees
}
