// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InsightsOverviewRequest struct {
	// Departments for which Insights are requested.
	Departments []string `json:"departments,omitempty"`
	// Manager emails whose teams should be filtered for. Empty array means no filtering.
	ManagerEmails []string `json:"managerEmails,omitempty"`
	DayRange      *Period  `json:"dayRange,omitempty"`
}

func (o *InsightsOverviewRequest) GetDepartments() []string {
	if o == nil {
		return nil
	}
	return o.Departments
}

func (o *InsightsOverviewRequest) GetManagerEmails() []string {
	if o == nil {
		return nil
	}
	return o.ManagerEmails
}

func (o *InsightsOverviewRequest) GetDayRange() *Period {
	if o == nil {
		return nil
	}
	return o.DayRange
}
