// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListAgentsResponse - List of all agents and their metadata.
type ListAgentsResponse struct {
	Agents []AgentResult `json:"agents,omitempty"`
}

func (o *ListAgentsResponse) GetAgents() []AgentResult {
	if o == nil {
		return nil
	}
	return o.Agents
}
