// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type ListEntitiesRequestEntityType string

const (
	ListEntitiesRequestEntityTypePeople         ListEntitiesRequestEntityType = "PEOPLE"
	ListEntitiesRequestEntityTypeTeams          ListEntitiesRequestEntityType = "TEAMS"
	ListEntitiesRequestEntityTypeCustomEntities ListEntitiesRequestEntityType = "CUSTOM_ENTITIES"
)

func (e ListEntitiesRequestEntityType) ToPointer() *ListEntitiesRequestEntityType {
	return &e
}
func (e *ListEntitiesRequestEntityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PEOPLE":
		fallthrough
	case "TEAMS":
		fallthrough
	case "CUSTOM_ENTITIES":
		*e = ListEntitiesRequestEntityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEntitiesRequestEntityType: %v", v)
	}
}

type ListEntitiesRequestIncludeField string

const (
	ListEntitiesRequestIncludeFieldPeople            ListEntitiesRequestIncludeField = "PEOPLE"
	ListEntitiesRequestIncludeFieldTeams             ListEntitiesRequestIncludeField = "TEAMS"
	ListEntitiesRequestIncludeFieldPeopleDistance    ListEntitiesRequestIncludeField = "PEOPLE_DISTANCE"
	ListEntitiesRequestIncludeFieldPermissions       ListEntitiesRequestIncludeField = "PERMISSIONS"
	ListEntitiesRequestIncludeFieldFacets            ListEntitiesRequestIncludeField = "FACETS"
	ListEntitiesRequestIncludeFieldInviteInfo        ListEntitiesRequestIncludeField = "INVITE_INFO"
	ListEntitiesRequestIncludeFieldLastExtensionUse  ListEntitiesRequestIncludeField = "LAST_EXTENSION_USE"
	ListEntitiesRequestIncludeFieldManagementDetails ListEntitiesRequestIncludeField = "MANAGEMENT_DETAILS"
	ListEntitiesRequestIncludeFieldUnprocessedTeams  ListEntitiesRequestIncludeField = "UNPROCESSED_TEAMS"
)

func (e ListEntitiesRequestIncludeField) ToPointer() *ListEntitiesRequestIncludeField {
	return &e
}
func (e *ListEntitiesRequestIncludeField) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PEOPLE":
		fallthrough
	case "TEAMS":
		fallthrough
	case "PEOPLE_DISTANCE":
		fallthrough
	case "PERMISSIONS":
		fallthrough
	case "FACETS":
		fallthrough
	case "INVITE_INFO":
		fallthrough
	case "LAST_EXTENSION_USE":
		fallthrough
	case "MANAGEMENT_DETAILS":
		fallthrough
	case "UNPROCESSED_TEAMS":
		*e = ListEntitiesRequestIncludeField(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEntitiesRequestIncludeField: %v", v)
	}
}

type ListEntitiesRequest struct {
	Filter []FacetFilter `json:"filter,omitempty"`
	// Use EntitiesSortOrder enum for SortOptions.sortBy
	Sort       []SortOptions                  `json:"sort,omitempty"`
	EntityType *ListEntitiesRequestEntityType `default:"PEOPLE" json:"entityType"`
	// The datasource associated with the entity type, most commonly used with CUSTOM_ENTITIES
	Datasource *string `json:"datasource,omitempty"`
	// A query string to search for entities that each entity in the response must conform to. An empty query does not filter any entities.
	Query *string `json:"query,omitempty"`
	// List of entity fields to return (that aren't returned by default)
	IncludeFields []ListEntitiesRequestIncludeField `json:"includeFields,omitempty"`
	// Hint to the server about how many results to send back. Server may return less.
	PageSize *int64 `json:"pageSize,omitempty"`
	// Pagination cursor. A previously received opaque token representing the position in the overall results at which to start.
	Cursor *string `json:"cursor,omitempty"`
	// A string denoting the search surface from which the endpoint is called.
	Source *string `json:"source,omitempty"`
}

func (l ListEntitiesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEntitiesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListEntitiesRequest) GetFilter() []FacetFilter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *ListEntitiesRequest) GetSort() []SortOptions {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *ListEntitiesRequest) GetEntityType() *ListEntitiesRequestEntityType {
	if o == nil {
		return nil
	}
	return o.EntityType
}

func (o *ListEntitiesRequest) GetDatasource() *string {
	if o == nil {
		return nil
	}
	return o.Datasource
}

func (o *ListEntitiesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListEntitiesRequest) GetIncludeFields() []ListEntitiesRequestIncludeField {
	if o == nil {
		return nil
	}
	return o.IncludeFields
}

func (o *ListEntitiesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListEntitiesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListEntitiesRequest) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}
