// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListEntitiesResponse struct {
	Results             []Person       `json:"results,omitempty"`
	TeamResults         []Team         `json:"teamResults,omitempty"`
	CustomEntityResults []CustomEntity `json:"customEntityResults,omitempty"`
	FacetResults        []FacetResult  `json:"facetResults,omitempty"`
	// Pagination cursor. A previously received opaque token representing the position in the overall results at which to start.
	Cursor *string `json:"cursor,omitempty"`
	// The total number of entities available
	TotalCount *int64 `json:"totalCount,omitempty"`
	// Whether or not more entities can be fetched.
	HasMoreResults *bool `json:"hasMoreResults,omitempty"`
	// Sort options from EntitiesSortOrder supported for this response. Default is empty list.
	SortOptions []EntitiesSortOrder `json:"sortOptions,omitempty"`
	// list of Person attributes that are custom setup by deployment
	CustomFacetNames []string `json:"customFacetNames,omitempty"`
}

func (o *ListEntitiesResponse) GetResults() []Person {
	if o == nil {
		return nil
	}
	return o.Results
}

func (o *ListEntitiesResponse) GetTeamResults() []Team {
	if o == nil {
		return nil
	}
	return o.TeamResults
}

func (o *ListEntitiesResponse) GetCustomEntityResults() []CustomEntity {
	if o == nil {
		return nil
	}
	return o.CustomEntityResults
}

func (o *ListEntitiesResponse) GetFacetResults() []FacetResult {
	if o == nil {
		return nil
	}
	return o.FacetResults
}

func (o *ListEntitiesResponse) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListEntitiesResponse) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *ListEntitiesResponse) GetHasMoreResults() *bool {
	if o == nil {
		return nil
	}
	return o.HasMoreResults
}

func (o *ListEntitiesResponse) GetSortOptions() []EntitiesSortOrder {
	if o == nil {
		return nil
	}
	return o.SortOptions
}

func (o *ListEntitiesResponse) GetCustomFacetNames() []string {
	if o == nil {
		return nil
	}
	return o.CustomFacetNames
}
