// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MoveCollectionItemResponse struct {
	Collection *Collection `json:"collection,omitempty"`
}

func (o *MoveCollectionItemResponse) GetCollection() *Collection {
	if o == nil {
		return nil
	}
	return o.Collection
}
