// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OperatorScope struct {
	Datasource *string `json:"datasource,omitempty"`
	DocType    *string `json:"docType,omitempty"`
}

func (o *OperatorScope) GetDatasource() *string {
	if o == nil {
		return nil
	}
	return o.Datasource
}

func (o *OperatorScope) GetDocType() *string {
	if o == nil {
		return nil
	}
	return o.DocType
}
