// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PerUserInsight struct {
	Person *Person `json:"person,omitempty"`
	// Total number of searches by this user over the specified time period.
	NumSearches *int64 `json:"numSearches,omitempty"`
	// Total number of chats by this user over the specified time period.
	NumChats *int64 `json:"numChats,omitempty"`
}

func (o *PerUserInsight) GetPerson() *Person {
	if o == nil {
		return nil
	}
	return o.Person
}

func (o *PerUserInsight) GetNumSearches() *int64 {
	if o == nil {
		return nil
	}
	return o.NumSearches
}

func (o *PerUserInsight) GetNumChats() *int64 {
	if o == nil {
		return nil
	}
	return o.NumChats
}
