// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type QueryInsightsResponse struct {
	// Unix timestamp of the last activity processed to make the response (in seconds since epoch UTC).
	LastLogTimestamp *int64 `json:"lastLogTimestamp,omitempty"`
	// Insights for queries.
	QueryInsights []QueryInsight `json:"queryInsights,omitempty"`
	// Insights for low performing queries without good results.
	LowPerformingQueryInsights []QueryInsight `json:"lowPerformingQueryInsights,omitempty"`
	// list of departments applicable for queries tab.
	Departments []string `json:"departments,omitempty"`
	// Min threshold in number of visitors while populating results, otherwise 0.
	MinVisitorThreshold *int64 `json:"minVisitorThreshold,omitempty"`
}

func (o *QueryInsightsResponse) GetLastLogTimestamp() *int64 {
	if o == nil {
		return nil
	}
	return o.LastLogTimestamp
}

func (o *QueryInsightsResponse) GetQueryInsights() []QueryInsight {
	if o == nil {
		return nil
	}
	return o.QueryInsights
}

func (o *QueryInsightsResponse) GetLowPerformingQueryInsights() []QueryInsight {
	if o == nil {
		return nil
	}
	return o.LowPerformingQueryInsights
}

func (o *QueryInsightsResponse) GetDepartments() []string {
	if o == nil {
		return nil
	}
	return o.Departments
}

func (o *QueryInsightsResponse) GetMinVisitorThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.MinVisitorThreshold
}
