// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RelatedQuestion struct {
	// The text of the related question
	Question *string `json:"question,omitempty"`
	// The answer for the related question
	Answer *string `json:"answer,omitempty"`
	// Subsections of the answer string to which some special formatting should be applied (eg. bold)
	Ranges []TextRange `json:"ranges,omitempty"`
}

func (o *RelatedQuestion) GetQuestion() *string {
	if o == nil {
		return nil
	}
	return o.Question
}

func (o *RelatedQuestion) GetAnswer() *string {
	if o == nil {
		return nil
	}
	return o.Answer
}

func (o *RelatedQuestion) GetRanges() []TextRange {
	if o == nil {
		return nil
	}
	return o.Ranges
}
