// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReminderRequest struct {
	// The document which the verification is for new reminders and/or update.
	DocumentID string `json:"documentId"`
	// The obfuscated id of the person this verification is assigned to.
	Assignee *string `json:"assignee,omitempty"`
	// Reminder for the next verifications in terms of days. For deletion, this will be omitted.
	RemindInDays *int64 `json:"remindInDays,omitempty"`
	// An optional free-text reason for the reminder. This is particularly useful when a reminder is used to ask for verification from another user (for example, "Duplicate", "Incomplete", "Incorrect").
	Reason *string `json:"reason,omitempty"`
}

func (o *ReminderRequest) GetDocumentID() string {
	if o == nil {
		return ""
	}
	return o.DocumentID
}

func (o *ReminderRequest) GetAssignee() *string {
	if o == nil {
		return nil
	}
	return o.Assignee
}

func (o *ReminderRequest) GetRemindInDays() *int64 {
	if o == nil {
		return nil
	}
	return o.RemindInDays
}

func (o *ReminderRequest) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}
