// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SearchClientConfig - Configuration settings related to Search
type SearchClientConfig struct {
	// Whether search is available or not.
	Available *bool `json:"available,omitempty"`
	// Custom autocomplete box placeholder to replace rotating prompts
	Placeholder *string `json:"placeholder,omitempty"`
}

func (o *SearchClientConfig) GetAvailable() *bool {
	if o == nil {
		return nil
	}
	return o.Available
}

func (o *SearchClientConfig) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}
