// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ShortcutInsight struct {
	Shortcut     Shortcut   `json:"shortcut"`
	VisitCount   *CountInfo `json:"visitCount,omitempty"`
	VisitorCount *CountInfo `json:"visitorCount,omitempty"`
}

func (o *ShortcutInsight) GetShortcut() Shortcut {
	if o == nil {
		return Shortcut{}
	}
	return o.Shortcut
}

func (o *ShortcutInsight) GetVisitCount() *CountInfo {
	if o == nil {
		return nil
	}
	return o.VisitCount
}

func (o *ShortcutInsight) GetVisitorCount() *CountInfo {
	if o == nil {
		return nil
	}
	return o.VisitorCount
}
