// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Error struct {
	Message *string `json:"message,omitempty"`
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SummarizeResponse struct {
	Error   *Error   `json:"error,omitempty"`
	Summary *Summary `json:"summary,omitempty"`
	// An opaque token that represents this summary in this particular query. To be used for /feedback reporting.
	TrackingToken *string `json:"trackingToken,omitempty"`
}

func (o *SummarizeResponse) GetError() *Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *SummarizeResponse) GetSummary() *Summary {
	if o == nil {
		return nil
	}
	return o.Summary
}

func (o *SummarizeResponse) GetTrackingToken() *string {
	if o == nil {
		return nil
	}
	return o.TrackingToken
}
