// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ContentChange - Configuration of content change trigger.
type ContentChange struct {
	// List of datasources enabled for content change triggers.
	EnabledDatasources []string `json:"enabledDatasources,omitempty"`
}

func (o *ContentChange) GetEnabledDatasources() []string {
	if o == nil {
		return nil
	}
	return o.EnabledDatasources
}

// TriggersClientConfig - Configuration settings for triggers.
type TriggersClientConfig struct {
	// Configuration of content change trigger.
	ContentChange *ContentChange `json:"contentChange,omitempty"`
}

func (o *TriggersClientConfig) GetContentChange() *ContentChange {
	if o == nil {
		return nil
	}
	return o.ContentChange
}
