// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateShortcutResponse struct {
	Shortcut *Shortcut      `json:"shortcut,omitempty"`
	Error    *ShortcutError `json:"error,omitempty"`
}

func (o *UpdateShortcutResponse) GetShortcut() *Shortcut {
	if o == nil {
		return nil
	}
	return o.Shortcut
}

func (o *UpdateShortcutResponse) GetError() *ShortcutError {
	if o == nil {
		return nil
	}
	return o.Error
}
