/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents a minimal summary of an action.
 */
export type ActionSummary = {
  /**
   * The unique identifier of the action.
   */
  toolId: string;
  /**
   * The display name of the action.
   */
  displayName: string;
  /**
   * The type of tool - RETRIEVAL for read-only operations, ACTION for operations that modify data.
   */
  type?: string | undefined;
  /**
   * The authentication type required - OAUTH_USER, OAUTH_ADMIN, API_KEY, BASIC_AUTH, DWD (domain-wide delegation), or NONE.
   */
  authType?: string | undefined;
  /**
   * For write actions only - REDIRECT (client renders URL) or EXECUTION (external server call).
   */
  writeActionType?: string | undefined;
  /**
   * Whether this action has been fully configured and validated.
   */
  isSetupFinished?: boolean | undefined;
  /**
   * Indicates the kind of knowledge a tool would access or modify.
   *
   * @remarks
   * Company knowledge:
   *   - Glean search, and any native tools that derive from it (e.g., expert search, code search)
   *   - Native federated tools to company data sources (e.g., outlook search)
   * World knowledge:
   *   - Platform action like bravewebsearch, geminiwebsearch, etc
   * Neutral knowledge:
   *   - Native tools that don't access or modify content via APIs (e.g., file analyst, think)
   *   - Platform read or write tools (creator has to determine their knowledge implications)
   */
  dataSource?: string | undefined;
};

/** @internal */
export const ActionSummary$inboundSchema: z.ZodType<
  ActionSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  tool_id: z.string(),
  display_name: z.string(),
  type: z.string().optional(),
  auth_type: z.string().optional(),
  write_action_type: z.string().optional(),
  is_setup_finished: z.boolean().optional(),
  data_source: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_id": "toolId",
    "display_name": "displayName",
    "auth_type": "authType",
    "write_action_type": "writeActionType",
    "is_setup_finished": "isSetupFinished",
    "data_source": "dataSource",
  });
});

/** @internal */
export type ActionSummary$Outbound = {
  tool_id: string;
  display_name: string;
  type?: string | undefined;
  auth_type?: string | undefined;
  write_action_type?: string | undefined;
  is_setup_finished?: boolean | undefined;
  data_source?: string | undefined;
};

/** @internal */
export const ActionSummary$outboundSchema: z.ZodType<
  ActionSummary$Outbound,
  z.ZodTypeDef,
  ActionSummary
> = z.object({
  toolId: z.string(),
  displayName: z.string(),
  type: z.string().optional(),
  authType: z.string().optional(),
  writeActionType: z.string().optional(),
  isSetupFinished: z.boolean().optional(),
  dataSource: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    toolId: "tool_id",
    displayName: "display_name",
    authType: "auth_type",
    writeActionType: "write_action_type",
    isSetupFinished: "is_setup_finished",
    dataSource: "data_source",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActionSummary$ {
  /** @deprecated use `ActionSummary$inboundSchema` instead. */
  export const inboundSchema = ActionSummary$inboundSchema;
  /** @deprecated use `ActionSummary$outboundSchema` instead. */
  export const outboundSchema = ActionSummary$outboundSchema;
  /** @deprecated use `ActionSummary$Outbound` instead. */
  export type Outbound = ActionSummary$Outbound;
}

export function actionSummaryToJSON(actionSummary: ActionSummary): string {
  return JSON.stringify(ActionSummary$outboundSchema.parse(actionSummary));
}

export function actionSummaryFromJSON(
  jsonString: string,
): SafeParseResult<ActionSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionSummary' from JSON`,
  );
}
