/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UpdateType,
  UpdateType$inboundSchema,
  UpdateType$outboundSchema,
} from "./updatetype.js";

export type DigestUpdate = {
  /**
   * URL link to the content or document.
   */
  url?: string | undefined;
  /**
   * Title or headline of the update.
   */
  title?: string | undefined;
  /**
   * Name or identifier of the data source (e.g., slack, confluence, etc.).
   */
  datasource?: string | undefined;
  /**
   * Brief summary or description of the update content.
   */
  summary?: string | undefined;
  /**
   * Optional type classification for the update.
   */
  type?: UpdateType | undefined;
};

/** @internal */
export const DigestUpdate$inboundSchema: z.ZodType<
  DigestUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
  title: z.string().optional(),
  datasource: z.string().optional(),
  summary: z.string().optional(),
  type: UpdateType$inboundSchema.optional(),
});

/** @internal */
export type DigestUpdate$Outbound = {
  url?: string | undefined;
  title?: string | undefined;
  datasource?: string | undefined;
  summary?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const DigestUpdate$outboundSchema: z.ZodType<
  DigestUpdate$Outbound,
  z.ZodTypeDef,
  DigestUpdate
> = z.object({
  url: z.string().optional(),
  title: z.string().optional(),
  datasource: z.string().optional(),
  summary: z.string().optional(),
  type: UpdateType$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigestUpdate$ {
  /** @deprecated use `DigestUpdate$inboundSchema` instead. */
  export const inboundSchema = DigestUpdate$inboundSchema;
  /** @deprecated use `DigestUpdate$outboundSchema` instead. */
  export const outboundSchema = DigestUpdate$outboundSchema;
  /** @deprecated use `DigestUpdate$Outbound` instead. */
  export type Outbound = DigestUpdate$Outbound;
}

export function digestUpdateToJSON(digestUpdate: DigestUpdate): string {
  return JSON.stringify(DigestUpdate$outboundSchema.parse(digestUpdate));
}

export function digestUpdateFromJSON(
  jsonString: string,
): SafeParseResult<DigestUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DigestUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DigestUpdate' from JSON`,
  );
}
