/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Different ways of sorting entities
 */
export const EntitiesSortOrder = {
  EntityName: "ENTITY_NAME",
  FirstName: "FIRST_NAME",
  LastName: "LAST_NAME",
  OrgSizeCount: "ORG_SIZE_COUNT",
  StartDate: "START_DATE",
  TeamSize: "TEAM_SIZE",
  Relevance: "RELEVANCE",
} as const;
/**
 * Different ways of sorting entities
 */
export type EntitiesSortOrder = ClosedEnum<typeof EntitiesSortOrder>;

/** @internal */
export const EntitiesSortOrder$inboundSchema: z.ZodNativeEnum<
  typeof EntitiesSortOrder
> = z.nativeEnum(EntitiesSortOrder);

/** @internal */
export const EntitiesSortOrder$outboundSchema: z.ZodNativeEnum<
  typeof EntitiesSortOrder
> = EntitiesSortOrder$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EntitiesSortOrder$ {
  /** @deprecated use `EntitiesSortOrder$inboundSchema` instead. */
  export const inboundSchema = EntitiesSortOrder$inboundSchema;
  /** @deprecated use `EntitiesSortOrder$outboundSchema` instead. */
  export const outboundSchema = EntitiesSortOrder$outboundSchema;
}
