/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnpublishAnnouncementRequest = {
  /**
   * The opaque id of the announcement to be unpublished.
   */
  id: number;
};

/** @internal */
export const UnpublishAnnouncementRequest$inboundSchema: z.ZodType<
  UnpublishAnnouncementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
});

/** @internal */
export type UnpublishAnnouncementRequest$Outbound = {
  id: number;
};

/** @internal */
export const UnpublishAnnouncementRequest$outboundSchema: z.ZodType<
  UnpublishAnnouncementRequest$Outbound,
  z.ZodTypeDef,
  UnpublishAnnouncementRequest
> = z.object({
  id: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnpublishAnnouncementRequest$ {
  /** @deprecated use `UnpublishAnnouncementRequest$inboundSchema` instead. */
  export const inboundSchema = UnpublishAnnouncementRequest$inboundSchema;
  /** @deprecated use `UnpublishAnnouncementRequest$outboundSchema` instead. */
  export const outboundSchema = UnpublishAnnouncementRequest$outboundSchema;
  /** @deprecated use `UnpublishAnnouncementRequest$Outbound` instead. */
  export type Outbound = UnpublishAnnouncementRequest$Outbound;
}

export function unpublishAnnouncementRequestToJSON(
  unpublishAnnouncementRequest: UnpublishAnnouncementRequest,
): string {
  return JSON.stringify(
    UnpublishAnnouncementRequest$outboundSchema.parse(
      unpublishAnnouncementRequest,
    ),
  );
}

export function unpublishAnnouncementRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnpublishAnnouncementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnpublishAnnouncementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnpublishAnnouncementRequest' from JSON`,
  );
}
