/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Shortcut,
  Shortcut$inboundSchema,
  Shortcut$Outbound,
  Shortcut$outboundSchema,
} from "./shortcut.js";
import {
  ShortcutError,
  ShortcutError$inboundSchema,
  ShortcutError$Outbound,
  ShortcutError$outboundSchema,
} from "./shortcuterror.js";

export type UpdateShortcutResponse = {
  shortcut?: Shortcut | undefined;
  error?: ShortcutError | undefined;
};

/** @internal */
export const UpdateShortcutResponse$inboundSchema: z.ZodType<
  UpdateShortcutResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  shortcut: Shortcut$inboundSchema.optional(),
  error: ShortcutError$inboundSchema.optional(),
});

/** @internal */
export type UpdateShortcutResponse$Outbound = {
  shortcut?: Shortcut$Outbound | undefined;
  error?: ShortcutError$Outbound | undefined;
};

/** @internal */
export const UpdateShortcutResponse$outboundSchema: z.ZodType<
  UpdateShortcutResponse$Outbound,
  z.ZodTypeDef,
  UpdateShortcutResponse
> = z.object({
  shortcut: Shortcut$outboundSchema.optional(),
  error: ShortcutError$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateShortcutResponse$ {
  /** @deprecated use `UpdateShortcutResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateShortcutResponse$inboundSchema;
  /** @deprecated use `UpdateShortcutResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateShortcutResponse$outboundSchema;
  /** @deprecated use `UpdateShortcutResponse$Outbound` instead. */
  export type Outbound = UpdateShortcutResponse$Outbound;
}

export function updateShortcutResponseToJSON(
  updateShortcutResponse: UpdateShortcutResponse,
): string {
  return JSON.stringify(
    UpdateShortcutResponse$outboundSchema.parse(updateShortcutResponse),
  );
}

export function updateShortcutResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateShortcutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateShortcutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateShortcutResponse' from JSON`,
  );
}
