/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IndexingShortcut,
  IndexingShortcut$inboundSchema,
  IndexingShortcut$Outbound,
  IndexingShortcut$outboundSchema,
} from "./indexingshortcut.js";

/**
 * Describes the request body of the /uploadshortcuts API call
 */
export type UploadShortcutsRequest = {
  /**
   * Unique id that must be used for this bulk upload instance
   */
  uploadId: string;
  /**
   * true if this is the first page of the upload. Defaults to false
   */
  isFirstPage?: boolean | undefined;
  /**
   * true if this is the last page of the upload. Defaults to false
   */
  isLastPage?: boolean | undefined;
  /**
   * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
   */
  forceRestartUpload?: boolean | undefined;
  /**
   * Batch of shortcuts information
   */
  shortcuts: Array<IndexingShortcut>;
};

/** @internal */
export const UploadShortcutsRequest$inboundSchema: z.ZodType<
  UploadShortcutsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uploadId: z.string(),
  isFirstPage: z.boolean().optional(),
  isLastPage: z.boolean().optional(),
  forceRestartUpload: z.boolean().optional(),
  shortcuts: z.array(IndexingShortcut$inboundSchema),
});

/** @internal */
export type UploadShortcutsRequest$Outbound = {
  uploadId: string;
  isFirstPage?: boolean | undefined;
  isLastPage?: boolean | undefined;
  forceRestartUpload?: boolean | undefined;
  shortcuts: Array<IndexingShortcut$Outbound>;
};

/** @internal */
export const UploadShortcutsRequest$outboundSchema: z.ZodType<
  UploadShortcutsRequest$Outbound,
  z.ZodTypeDef,
  UploadShortcutsRequest
> = z.object({
  uploadId: z.string(),
  isFirstPage: z.boolean().optional(),
  isLastPage: z.boolean().optional(),
  forceRestartUpload: z.boolean().optional(),
  shortcuts: z.array(IndexingShortcut$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadShortcutsRequest$ {
  /** @deprecated use `UploadShortcutsRequest$inboundSchema` instead. */
  export const inboundSchema = UploadShortcutsRequest$inboundSchema;
  /** @deprecated use `UploadShortcutsRequest$outboundSchema` instead. */
  export const outboundSchema = UploadShortcutsRequest$outboundSchema;
  /** @deprecated use `UploadShortcutsRequest$Outbound` instead. */
  export type Outbound = UploadShortcutsRequest$Outbound;
}

export function uploadShortcutsRequestToJSON(
  uploadShortcutsRequest: UploadShortcutsRequest,
): string {
  return JSON.stringify(
    UploadShortcutsRequest$outboundSchema.parse(uploadShortcutsRequest),
  );
}

export function uploadShortcutsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UploadShortcutsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadShortcutsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadShortcutsRequest' from JSON`,
  );
}
